* Linux 技巧
  http://blog.jobbole.com/60549/
** 挂载exfat格式的U盘(ubuntu 1404)
   sudo apt-add-repository ppa:relan/exfat
   sudo apt-get update
   sudo apt-get install exfat-utils exfat-fuse
* Linux 命令
** 查看系统信息
   w： display who is online
   whoami: who you are logged in
   finger user: display information about user
   cat /proc/cpuinfo: cpu info
   cat /proc/meminfo: memory information
** 压缩和解压缩
   tar cf file.tar files: create a tar named file.tar containing files
   tar xf file.tar: extract the files from file.tar
   tar czf file.tar.gz files: create a tar with gzip compression
   tar xzf file.tar.gz extract a tar using gzip
   tar cjf file.tar.bz2 create a tar with bzip2 compression
   tar xjf file.tar.bz2 extract a tar using bzip2
   gzip file compress file and renames it to file.gz, 会删除原来的file文件
   gzip -d file.gz decompress file.gz back to file， 会删除file.gz文件
** network
   whois domain: get whois information for domain
   dig domain: get DNS information for domain
   dig -x host: reverse lookup host
   wget -c url: continue a stopped download
** installation
   dpkg -i pkg.deb : install a package(debian)
   rpm -Uvh pkg.rpm : install a package(RPM)
   
** 常用命令
   sudo !! #以root用户执行上一条命令
   mtr google.com
   altr + . #调出上一次命令使用的最后一个参数
   man ascii #快速查看ascii的值
   curl #获取外部ip地址
** htop
   sudo aptitude install htop
** ip 命令
   linux中的ip命令和ifconfig类似，但是功能更加强大，ifconfig是net-tools中被废弃使用的一个命令
   ip是iproute2套件中一个命令，大多数的linux发行版本已经预装了iproute2，
   源码地址：https://kernel.googlesource.com/pub/scm/linux/kernel/git/shemminger/iproute2.git
   基本使用方法：
   设置ip： sudo ip addr add ip/24 dev wlan0,注意：/24用于在无类域内路由选择（CIDR）中来显示
   所用的子网掩码。
   查看上述方式设置的ip是否生效： ip addr show wlan0
   删除ip地址： sudo ip addr del ip/24 dev wlan0
   列出路由表条目： ip route show
   获取ip地址从那个路由包过来： ip route get ip
   更改默认路由： sudo ip route add default via ip
   显示网络统计数据： ip -s link
   ip -s -s link ls p2p1：获取一个特定网络接口的信息，在网络接口名字后添加选项ls即可，使用多个
   -s选项给该特定接口更详细的信息。
   ip neighbour：地址解析
   ip monitor all：监控netlink消息
   激活或停止网络接口： sudo ip link set ppp0 down：停止，sudo ip link set ppp0 up：激活
   ip route help: 获取route的帮助
*** 使用
    选中某个进程按下空格键可以高亮选中的进程，
    -s：按指定的列排列。htop -s PID
    -u：显示指定用户的进程信息列表， htop -u uname
    -d：设置刷新时间，htop -d 100，注意：-d的单位是10微妙, -d 100就是1秒时间
* Linux系统无效文件删除
  http://www.ibm.com/developerworks/cn/linux/1310_caoyq_linuxdelete/index.html
  find . -nouser | xargs rm -rf #删除当前目录下没有user的文件
** fdupes工具
   fdupes 是一个命令行工具，它会查找和删除指定目录的重复文件，
   它通过文件的大小和 MD5 值进行比较 。一个字节一个字节进行对比。
   apt-get install fdupes
   在/etc查找重复文件： fdupes /etc
   与linux命令组合使用，删除文件：
   fdupes -r -f . | grep -v ^$ | tee duplicate.txt cat duplicate.txt | \
   while read file; do rm -v "$file"; done
   也可以与sed命令组合使用，删除文件：
   fdupes -r -n -S /tmp | sed -r "s/^/#rm \"/" | sed -r "s/$/\"/" > duplicate.sh
** 删除缓存文件
   apt-get autoclean 清理旧版本的软件缓存
   apt-get clean 清理所有软件缓存
** geeqie工具
   该工具可以找出相似图像文件，
   apt-get install gqview
** BleachBit
   BleachBit 是一款开源免费的系统清理工具，功能类似 Windows 平台的 CCleaner。
   BleachBit 能够删除隐藏的垃圾文件，以及简单的保护你的隐私。
   擦除缓存，删除 cookies 文件，清除互联网浏览历史，删除未使用的本地化碎片日志，
   删除临时文件，是一款非常实用的跨平台的系统清理工具.
   apt-get install bleachbit   
   
** 检查收集Linux硬件信息
*** lscpu
    用于查询cpu信息
*** lshw
    显示硬件信息表，lshw可能需要安装，下载源码使用make，make install
    lshw -sort
*** hwinfo
    需要安装， hwinfo -short
*** lspci
    列出PCI总线的信息以及连接到PCI总线上的设备信息
*** lsusb
    列出usb控制器的设备信息
*** lsblk
    列出块设备的信息
*** lsscsi
    列出scsi/sdat设备的信息， 如硬盘驱动器，光盘驱动器
* 其他
** Ubuntu下自动安装雅黑字体
   http://blog.prosight.me/blogs/722/
* 简单的SSH渗透技巧
  http://www.tuicool.com/articles/rQj632J
* Man Page
** 各个section的含义
   1：用户命令  2：系统调用
   3：库函数    4：特殊文件，如null
   5：系统配置文件  6：游戏
   7：其他杂项，如：bash-builtins
   8：系统命令，如：ifconfig
   用户命令通常位于/bin和/usr/bin目录下，系统管理命令通常位于/sbin和/usr/sbin目录
   如果想查看库函数的printf，则使用man 3 printf

* 同步ubuntu的系统时间
  ntpdate cn.pool.ntp.org 
  hwclock --systohc, 将系统时间写入硬件时间
* 软件自启动
  init并不是直接在/etc/init.d目录下找各个服务的启动脚本，而是在/etc/rcX.d/目录下查找，
  该目录包含rc0.d,rc1.d等分别代表不同的init启动级别的子目录。
  可以使用runlevel命令查看当前你的系统运行级别

  rcx.d的目录下所包含的内容，内容全是一些符号链接，链接到上一级init目录中的脚本上。
  这些符号链接名称都以S或K开头，后面跟一个数字以及该脚本所控制的服务名，
  例如S10network。 当init从低的运行级向高的运行级过渡时，
  它按照数字递增的顺序运行所有以S开头的脚本，S=start，即启动脚本对应的服务；
  K=kill，即杀死脚本对应服务
  中间这个数字十分重要，系统启动时按照这个数字递增执行所有S开头的脚本，
  系统关闭时按照这个数字递减执行所有K开头的脚本
* Ubuntu 技巧
** 添加ppa源
   方法1：图形化界面添加
   打开ubuntu的软件管理中心， 选择菜单栏中的“edit”=>"software sources", 弹出一个框
   选择“other software”页， 选择下方的“add”按钮，填上ppa源即可
   方法2：使用命令
   add-apt-repository ppa:xxxx
** ppa源名的确定
   1. 通过google： 搜索"软件名 + ppa"
   2. 直接到https://launchpad.net 搜索
   之后在页面中搜索ppa:xxx的字样
** sudo 免密码
   sudo visudo 或者 vi /etc/sudoers
   添加如下内容：
   用户名 ALL=(ALL) NOPASSWD:ALL
   %用户组名 ALL=(ALL) NOPASSWD:ALL
   sudoers文件的权限配置的格式如下
   %用户组名 主机名=(权限) 命令
   用户名 主机名=(权限) 命令
