* Linux 技巧
  http://blog.jobbole.com/60549/
* Linux 命令
** 查看系统信息
   w： display who is online
   whoami: who you are logged in
   finger user: display information about user
   cat /proc/cpuinfo: cpu info
   cat /proc/meminfo: memory information
** 压缩和解压缩
   tar cf file.tar files: create a tar named file.tar containing files
   tar xf file.tar: extract the files from file.tar
   tar czf file.tar.gz files: create a tar with gzip compression
   tar xzf file.tar.gz extract a tar using gzip
   tar cjf file.tar.bz2 create a tar with bzip2 compression
   tar xjf file.tar.bz2 extract a tar using bzip2
   gzip file compress file and renames it to file.gz, 会删除原来的file文件
   gzip -d file.gz decompress file.gz back to file， 会删除file.gz文件
** network
   whois domain: get whois information for domain
   dig domain: get DNS information for domain
   dig -x host: reverse lookup host
   wget -c url: continue a stopped download
** installation
   dpkg -i pkg.deb : install a package(debian)
   rpm -Uvh pkg.rpm : install a package(RPM)
   
* Linux系统无效文件删除
  http://www.ibm.com/developerworks/cn/linux/1310_caoyq_linuxdelete/index.html
  find . -nouser | xargs rm -rf #删除当前目录下没有user的文件
** fdupes工具
   fdupes 是一个命令行工具，它会查找和删除指定目录的重复文件，
   它通过文件的大小和 MD5 值进行比较 。一个字节一个字节进行对比。
   apt-get install fdupes
   在/etc查找重复文件： fdupes /etc
   与linux命令组合使用，删除文件：
   fdupes -r -f . | grep -v ^$ | tee duplicate.txt cat duplicate.txt | \
   while read file; do rm -v "$file"; done
   也可以与sed命令组合使用，删除文件：
   fdupes -r -n -S /tmp | sed -r "s/^/#rm \"/" | sed -r "s/$/\"/" > duplicate.sh
** 删除缓存文件
   apt-get autoclean 清理旧版本的软件缓存
   apt-get clean 清理所有软件缓存
** geeqie工具
   该工具可以找出相似图像文件，
   apt-get install gqview
** BleachBit
   BleachBit 是一款开源免费的系统清理工具，功能类似 Windows 平台的 CCleaner。
   BleachBit 能够删除隐藏的垃圾文件，以及简单的保护你的隐私。
   擦除缓存，删除 cookies 文件，清除互联网浏览历史，删除未使用的本地化碎片日志，
   删除临时文件，是一款非常实用的跨平台的系统清理工具.
   apt-get install bleachbit   
   
** 检查收集Linux硬件信息
*** lscpu
    用于查询cpu信息
*** lshw
    显示硬件信息表，lshw可能需要安装，下载源码使用make，make install
    lshw -sort
*** hwinfo
    需要安装， hwinfo -short
*** lspci
    列出PCI总线的信息以及连接到PCI总线上的设备信息
*** lsusb
    列出usb控制器的设备信息
*** lsblk
    列出块设备的信息
*** lsscsi
    列出scsi/sdat设备的信息， 如硬盘驱动器，光盘驱动器
* 其他
** Ubuntu下自动安装雅黑字体
   http://blog.prosight.me/blogs/722/
* 简单的SSH渗透技巧
  http://www.tuicool.com/articles/rQj632J
